server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: 123456

eureka:
  client:
    # 表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 单机版
      # defaultZone: http://localhost:8071/eureka
      # 集群版
      defaultZone: http://eureka-server-8071:8071/eureka,http://eureka-server-8072:8072/eureka,
  instance:
    # 之前我们Status显示的是calmness是我的主机名，我们不想显示主机名可以添加如下配置,这样status就是显示order8081
    instance-id: order8081
    # 访问路径可以显示IP地址，我们点击order8081，设置为true的时候出现的访问地址是ip，否则为calmness主机名
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 10
    # Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒(默认是90秒)，超过则剔除（客户端告诉服务端按照此规则等待自己）
    # 必须大于lease-renewal-interval-in-seconds 不然还没注册就被剔除了
    lease-expiration-duration-in-seconds: 15

feign:
  client:
    config:
      default:
        # 指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
        connectTimeout: 5000
        # 指的是建立连接后从服务器读取到可用资源所用的时间
        readTimeout: 5000
  hystrix:
    enabled: true
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.calm.service.PaymentFeignService: debug