server:
  port: 8001
spring:
  application:
    name: order-service-8081
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: root